version: 0.0
os: linux

files:
  - source: /target/Murshedi-0.0.1-SNAPSHOT.jar # Adjust this if your JAR name/path is different after 'mvn package'
    destination: /opt/codedeploy-agent/deployment-root/murshedi-backend/
  - source: /scripts/ # This will copy the entire 'scripts' directory
    destination: /opt/codedeploy-agent/deployment-root/murshedi-backend/scripts/

permissions:
  - object: /opt/codedeploy-agent/deployment-root/murshedi-backend/scripts/
    pattern: "*.sh"
    mode: 755
    owner: ec2-user # Or the user your application will run as
    type:
      - file

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ec2-user
